name: Go

on:
  push:
    branches:
     - master
  pull_request:

jobs:

  test_and_build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        stable: check-latest
        
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Test
      run: go test -v -count=1 ./...
